package modelo.entidades;
// Generated 11-feb-2021 18:18:30 by Hibernate Tools 5.2.12.Final

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Autorlibro generated by hbm2java
 */
@Entity
@Table(name = "Autorlibro")
public class Autorlibro implements java.io.Serializable {

	private AutorlibroId id;

	public Autorlibro() {
	}

	public Autorlibro(AutorlibroId id) {
		this.id = id;
	}

	public AutorlibroId getId() {
		return this.id;
	}

	public void setId(AutorlibroId id) {
		this.id = id;
	}

}
