package modelo.entidades;
// Generated 12-feb-2021 20:59:22 by Hibernate Tools 5.2.12.Final

/**
 * Autorlibro generated by hbm2java
 */
public class Autorlibro implements java.io.Serializable {

	private AutorlibroId id;

	public Autorlibro() {
	}

	public Autorlibro(AutorlibroId id) {
		this.id = id;
	}

	public AutorlibroId getId() {
		return this.id;
	}

	public void setId(AutorlibroId id) {
		this.id = id;
	}

}
