package modelo.entidades;
// Generated 12-feb-2021 20:59:22 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AutorlibroId generated by hbm2java
 */
@Entity
@Table(name = "AutorlibroId")
public class AutorlibroId implements java.io.Serializable {

	@Id
	@Column (name="idAutor")
	private int idAutor;
	@Column (name="codLibro")
	private String codLibro;

	public AutorlibroId() {
	}

	public AutorlibroId(int idAutor, String codLibro) {
		this.idAutor = idAutor;
		this.codLibro = codLibro;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public String getCodLibro() {
		return this.codLibro;
	}

	public void setCodLibro(String codLibro) {
		this.codLibro = codLibro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutorlibroId))
			return false;
		AutorlibroId castOther = (AutorlibroId) other;

		return (this.getIdAutor() == castOther.getIdAutor())
				&& ((this.getCodLibro() == castOther.getCodLibro()) || (this.getCodLibro() != null
						&& castOther.getCodLibro() != null && this.getCodLibro().equals(castOther.getCodLibro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAutor();
		result = 37 * result + (getCodLibro() == null ? 0 : this.getCodLibro().hashCode());
		return result;
	}

}
