package modelo.entidades;
// Generated 12-feb-2021 20:59:22 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Autor generated by hbm2java
 */
@Entity
@Table(name = "Autor")
public class Autor implements java.io.Serializable {

	@Id
	@Column (name="idAutor")
	private int idAutor;
	@Column (name="nombre")
	private String nombre;
	@Column (name="apellidos")
	private String apellidos;
	@ManyToMany
	private Set<Libro> libros = new HashSet<Libro>(0);

	public Autor() {
	}

	public Autor(int idAutor, String nombre, String apellidos) {
		this.idAutor = idAutor;
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

}
