package modelo.entidades;
// Generated 12-feb-2021 20:59:22 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contactousuario generated by hbm2java
 */
@Entity
@Table(name = "Contactousuario")
public class Contactousuario implements java.io.Serializable {

	@Id
	@Column (name="id")
	private ContactousuarioId id;

	public Contactousuario() {
	}

	public Contactousuario(ContactousuarioId id) {
		this.id = id;
	}

	public ContactousuarioId getId() {
		return this.id;
	}

	public void setId(ContactousuarioId id) {
		this.id = id;
	}

}
