package modelo.entidades;
// Generated 11-feb-2021 18:18:30 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ejemplar generated by hbm2java
 */
@Entity
@Table(name = "Ejemplar")
public class Ejemplar implements java.io.Serializable {

	private int idEjemplar;
	private Libro libro;
	private int numEjemplar;
	private String estado;
	private Set prestamosForIdEjemplar = new HashSet(0);
	private Set prestamosForIdUsuario = new HashSet(0);

	public Ejemplar() {
	}

	public Ejemplar(int idEjemplar, Libro libro, int numEjemplar, String estado) {
		this.idEjemplar = idEjemplar;
		this.libro = libro;
		this.numEjemplar = numEjemplar;
		this.estado = estado;
	}

	public Ejemplar(int idEjemplar, Libro libro, int numEjemplar, String estado, Set prestamosForIdEjemplar,
			Set prestamosForIdUsuario) {
		this.idEjemplar = idEjemplar;
		this.libro = libro;
		this.numEjemplar = numEjemplar;
		this.estado = estado;
		this.prestamosForIdEjemplar = prestamosForIdEjemplar;
		this.prestamosForIdUsuario = prestamosForIdUsuario;
	}

	public int getIdEjemplar() {
		return this.idEjemplar;
	}

	public void setIdEjemplar(int idEjemplar) {
		this.idEjemplar = idEjemplar;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public int getNumEjemplar() {
		return this.numEjemplar;
	}

	public void setNumEjemplar(int numEjemplar) {
		this.numEjemplar = numEjemplar;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getPrestamosForIdEjemplar() {
		return this.prestamosForIdEjemplar;
	}

	public void setPrestamosForIdEjemplar(Set prestamosForIdEjemplar) {
		this.prestamosForIdEjemplar = prestamosForIdEjemplar;
	}

	public Set getPrestamosForIdUsuario() {
		return this.prestamosForIdUsuario;
	}

	public void setPrestamosForIdUsuario(Set prestamosForIdUsuario) {
		this.prestamosForIdUsuario = prestamosForIdUsuario;
	}

}
