package modelo.entidades;

// Generated 12-feb-2021 20:59:22 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ejemplar generated by hbm2java
 */
@Entity
@Table(name = "Ejemplar")
public class Ejemplar implements java.io.Serializable {

	@Id
	@Column (name="idEjemplar")
	private int idEjemplar;
	@Column (name="libro")
	private Libro libro;
	@Column (name="numEjemplar")
	private int numEjemplar;
	@Column (name="estado")
	private String estado;
	
	
	@OneToMany
	private Set <Prestamo>prestamosForIdEjemplar = new  HashSet<Prestamo>(0);
	@OneToMany
	private Set <Prestamo>prestamosForIdUsuario = new  HashSet<Prestamo>(0);

	public Ejemplar() {
	}

	public Ejemplar(int idEjemplar, Libro libro, int numEjemplar, String estado) {
		this.idEjemplar = idEjemplar;
		this.libro = libro;
		this.numEjemplar = numEjemplar;
		this.estado = estado;
	}

	public Ejemplar(int idEjemplar, Libro libro, int numEjemplar, String estado, Set prestamosForIdEjemplar,
			Set prestamosForIdUsuario) {
		this.idEjemplar = idEjemplar;
		this.libro = libro;
		this.numEjemplar = numEjemplar;
		this.estado = estado;
		this.prestamosForIdEjemplar = prestamosForIdEjemplar;
		this.prestamosForIdUsuario = prestamosForIdUsuario;
	}

	public int getIdEjemplar() {
		return this.idEjemplar;
	}

	public void setIdEjemplar(int idEjemplar) {
		this.idEjemplar = idEjemplar;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public int getNumEjemplar() {
		return this.numEjemplar;
	}

	public void setNumEjemplar(int numEjemplar) {
		this.numEjemplar = numEjemplar;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getPrestamosForIdEjemplar() {
		return this.prestamosForIdEjemplar;
	}

	public void setPrestamosForIdEjemplar(Set prestamosForIdEjemplar) {
		this.prestamosForIdEjemplar = prestamosForIdEjemplar;
	}

	public Set getPrestamosForIdUsuario() {
		return this.prestamosForIdUsuario;
	}

	public void setPrestamosForIdUsuario(Set prestamosForIdUsuario) {
		this.prestamosForIdUsuario = prestamosForIdUsuario;
	}

}
