package modelo.entidades;
// Generated 12-feb-2021 20:59:22 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prestamo generated by hbm2java
 */
@Entity
@Table(name = "Prestamo")
public class Prestamo implements java.io.Serializable {

	@Id
	@Column (name="idPrestamo")
	private int idPrestamo;
	@Column (name="ejemplarByIdEjemplar")
	private Ejemplar ejemplarByIdEjemplar;
	@Column (name="ejemplarByIdUsuario")
	private Ejemplar ejemplarByIdUsuario;
	@Column (name="fechaPrestamo")
	private Date fechaPrestamo;
	@Column (name="fechaDevolucion")
	private Date fechaDevolucion;

	public Prestamo() {
	}

	public Prestamo(int idPrestamo, Ejemplar ejemplarByIdEjemplar, Ejemplar ejemplarByIdUsuario, Date fechaPrestamo,
			Date fechaDevolucion) {
		this.idPrestamo = idPrestamo;
		this.ejemplarByIdEjemplar = ejemplarByIdEjemplar;
		this.ejemplarByIdUsuario = ejemplarByIdUsuario;
		this.fechaPrestamo = fechaPrestamo;
		this.fechaDevolucion = fechaDevolucion;
	}

	public int getIdPrestamo() {
		return this.idPrestamo;
	}

	public void setIdPrestamo(int idPrestamo) {
		this.idPrestamo = idPrestamo;
	}

	public Ejemplar getEjemplarByIdEjemplar() {
		return this.ejemplarByIdEjemplar;
	}

	public void setEjemplarByIdEjemplar(Ejemplar ejemplarByIdEjemplar) {
		this.ejemplarByIdEjemplar = ejemplarByIdEjemplar;
	}

	public Ejemplar getEjemplarByIdUsuario() {
		return this.ejemplarByIdUsuario;
	}

	public void setEjemplarByIdUsuario(Ejemplar ejemplarByIdUsuario) {
		this.ejemplarByIdUsuario = ejemplarByIdUsuario;
	}

	public Date getFechaPrestamo() {
		return this.fechaPrestamo;
	}

	public void setFechaPrestamo(Date fechaPrestamo) {
		this.fechaPrestamo = fechaPrestamo;
	}

	public Date getFechaDevolucion() {
		return this.fechaDevolucion;
	}

	public void setFechaDevolucion(Date fechaDevolucion) {
		this.fechaDevolucion = fechaDevolucion;
	}

}
